### ISSUE TITLE
how to uninstall...? 

### ISSUE THREAD

**Issue by nichu8** [Bhai4You/Crazy-Banner#1]
i can't uninstall this..

**Comment by khansaad1275** [comment]
I was also struggling with the same problem and then I found a perfect solution and then i wrote a blog on : [[How to Remove Crazy-Banner in Termux in just 3 simple steps](https://www.learntermux.tech/2020/01/evil-eye-permanent-banner-in-termux.html)]

**Comment by harshal7499** [comment]
I also want to uninstall it but i can't do that please tell us bro

**Comment by khansaad1275** [comment]
> I also want to uninstall it but i can't do that please tell us bro
https://www.learntermux.tech/2020/01/evil-eye-permanent-banner-in-termux.html

**Comment by Bhai4You** [comment]
`pkg install wget -y;cd $HOME;wget https://raw.githubusercontent.com/Bhai4You/Termux-Banner/master/remove.sh;bash remove.sh`

copy above code and paste in termux !!

**Comment by Akhiljose321** [comment]
https://raw.githubusercontent.com/Bhai4You/Termux-Banner/master/remove.sh;bash remove.sh
